version: '3'

services:
  postgres:
    image: 'postgres:10-alpine'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  webpack:
    build: .
    env_file:
      - '.env'
    command: script/start_webpacker.sh
    volumes:
      - '.:/app'
      - gems:/bundle
    ports:
      - '3035:3035'

  web:
    depends_on:
      - 'postgres'
      - 'webpack'
    build: .
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    command: script/start.sh
    volumes:
      - '.:/app'
      - gems:/bundle
    env_file:
      - '.env'

  bundle:
    image: busybox
    volumes:
      - gems:/bundle

volumes:
  redis:
  postgres:
  webpack:
  gems:
