default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password: 
  pool: 5

development:
  <<: *default
  database: spree_development

test:
  <<: *default
  database: spree_test

production:
  <<: *default
  database: spree_production
